### PR TITLE
Job Posting for OpenDP

### PR DESCRIPTION
**Pull request by anniewu332**
Hi,

I'm the Program Director of the OpenDP project (github.com/opendp/).  We have an opening for an open-source community manager.  Please help share it.  Thanks in advance!

Best,
Annie Wu

### CODE REVIEW

**Comment by Shoeboxam** [comment]
What is the status of this? Is this repo still being maintained?

**Comment by stefanv** [comment]
@Shoeboxam Yes, sorry, I ran into an issue building with the latest JS dependencies, and haven't gotten around to fixing it. I'll take a look today.

**Comment by Shoeboxam** [comment]
No worries! Let me know if trimming or adjusting the job posting might help avoid the issue.

**Comment by stefanv** [comment]
@Shoeboxam @anniewu332 Your post is now at https://jobs.numfocus.org/ with permalink https://jobs.numfocus.org/job/2022-09-02_opendp

It would be great if you could make the post a bit shorter; as you see it doesn't render well when it's so long.

**Pull request merged**
