### PR TITLE
Added a TUD/SymPy CZI position.

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by stefanv** [comment]
Hi Jason, thanks for the job post!  The indentation in the yaml isn't quite right (text should be offset in the description section.  Also, the post is very long—you can take a look at the [current posts](https://jobs.numfocus.org/) for a rough idea of length and how that renders—would you be able to shorten it a bit?

Thanks!

**Comment by moorepants** [comment]
I will fix the indentation. I can shorten it, but this is the approved job text from my university. I'd rather keep it as is.

**Comment by moorepants** [comment]
I think I see why you ask about the length. Is it because the entirety of the post displays on the front page?

**Comment by moorepants** [comment]
Ok, I see how others linked to the full posts. I have indented and shortened.

**Comment by moorepants** [comment]
Hi @stefanv, any chance this could be merged? I only have two weeks left for applications.

**Comment by stefanv** [comment]
Sorry, @moorepants, this got lost somewhere in all my notifications. Merging now.

**Comment by stefanv** [comment]
Post is on the board with permalink https://jobs.numfocus.org/job/2022-02-04_sympy

**Comment by moorepants** [comment]
Thanks!

**Pull request merged**
