### PR TITLE
Add charter

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Review by aterrel — COMMENTED** [review]
It would be good to say who is in charge of the board and how decisions get made on what goes on. You know "Lead Openly" =P

**Comment by stefanv** [comment]
> It would be good to say who is in charge of the board and how decisions get made on what goes on. You know "Lead Openly" =P

It currently says that two NF staff members have to approve posts, and that the board are in control of the process.  Do we need to specify something in addition to that?

**Comment by aterrel** [comment]
> > It would be good to say who is in charge of the board and how decisions get made on what goes on. You know "Lead Openly" =P
> 
> It currently says that two NF staff members have to approve posts, and that the board are in control of the process. Do we need to specify something in addition to that?

Ah sorry, I missed that. I think that works but two NF staff members might be burdensome. I'll let @lsilen determine that.

Thanks for building this system!

**Comment by lsilen** [comment]
Yes, one staff member approving would be best. We could also leave that open by stating -  NumFOCUS staff will be responsible for approving posts.
Can _advertising_ be replaced with _promoting_ to avoid any assumption that there's a cost associated with the benefit of posting for donors?

**Comment by stefanv** [comment]
@lsilen I updated the text to allow for staff to approve.

I prefer "advertise" over "promote", because I don't think we actively promote, but we do give visibility to (advertise).

**Comment by stefanv** [comment]
The final version was reviewed by Leah.

**Pull request merged**
